### ISSUE TITLE
ALL IS BROKEN

### ISSUE THREAD

**Issue by ietres** [RaymondWang987/VDW_Dataset_Toolkits#2]
Hello,

I wanted to provide some feedback on your repository. Unfortunately, I have found it to be very problematic and it has caused a lot of wasted time. There are significant issues that need to be addressed for it to be useful.

I hope you can take this feedback into consideration and make the necessary improvements. Thank you.

**Comment by RaymondWang987** [comment]
You are being very rude and you do not specify any problem. You cannot install the envs since it is complicated, which does not mean that the code is problematic and not useful. Building the data is challenging and difficult, which takes us many months to complete. Who are you here to judging us? Who are you? Dare u tell me????
